### ISSUE TITLE
Not able to generate token for EX30

### ISSUE THREAD

**Issue by drojasvela** [evcc-io/evcc.io#38]
Hi! I was trying to generate the token for my Volvo EX30 following the steps described in https://docs.evcc.io/en/docs/devices/vehicles#volvo and when executing the command `evcc -c /config/evcc.yaml token EX30` I get the following error:

```
main  ] INFO 2025/04/16 23:02:22 using config file: /config/evcc.yaml
[main  ] FATAL 2025/04/16 23:02:22 decoding failed due to the following error(s):

'' has invalid keys: capacity, icon, title, tokens, vccapikey, vin
```

My current evcc.yaml file looks like this in the vehicle section:

```
vehicles:
  - name: EX30
    type: template
    template: volvo-connected
    title: Volvo EX30 # Will be displayed in the user interface (optional)
    capacity: 66 # Battery capacity in kWh (optional)
    vccapikey: MY_REAL_KEY # Volvo developer portal VCC API Key
    clientId: MY_REAL_ID # Client ID of your [Volvo Developer App](https://developer.volvocars.com/).
    clientSecret: MY_REAL_SECRET # Client Secret of your [Volvo Developer App](https://developer.volvocars.com/).
    accessToken:
    refreshToken:
    vin: MY_VIN
```

I've tried removing the accessToken and refreshToken lines as well as triple checked the keys from the volvo developer portal and everyhting looks good but still I can't figure out why I keep getting the error in the terminal when I run the `evcc -c /config/evcc.yaml token EX30` command.

Thanks a lot in advance!
- Diego
